version: '3.7'
name: pentestify

services:

  main:
    image: pentestify-main
    build:
      dockerfile: etc/docker/Dockerfile
      context: ../../
    container_name: main
    volumes:
      - ../../:/app

  postgres:
    image: postgres:15.4
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - psql-data:/var/lib/postgresql/data

#  web-server:
#    image: pentestify-main
#    container_name: web-server
#    volumes:
#      - ../../:/app
#    command: python3 src/server.py
#    ports:
#      - "8000:8000"





volumes:
  psql-data:
    driver: local
